version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run: sudo apt-get install libusb-1.0-0-dev libudev-dev
      - run: python setup.py test
      - run: python setup.py build sdist

  deploy-pypi:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run: sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      - run:
          name: Install Tools
          command: |
            python -m venv temp
            . temp/bin/activate
            pip install -U pip setuptools
            pip install -U twine
      - run:
          name: Build
          command: |
            . temp/bin/activate
            python setup.py build sdist
      - run:
          name: Upload
          command: |
            . temp/bin/activate
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-pypi:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
